### ISSUE TITLE
下半身のeusモデル

### ISSUE THREAD

**Issue by hyaguchijsk** [seed-solutions/aero-ros-pkg#123]
現状のeusがあんまりにもあんまりなので，なんとかできないかな．

まずurdfからeusに直接持ってくるのは，
ヒューマノイドでないためにむずかしそう．

そもそも上下で二台の別のロボットを連結して使っているという四脚時代の名残があり，
それはできればまた四脚に戻したいなど起こった時に拡張性として残したい．

eusモデルだけなら，
単純に下半身だけモデルを作って上半身をassocしてしまえばいい．
ただしurdfが変わった時に手動でやりましょう，というのは嫌．

そもそも #115 が未解決．

**Comment by YoheiKakiuchi** [comment]
aeroeus moves to https://github.com/jsk-ros-pkg/jsk_robot/pull/906
