### ISSUE TITLE
KineticのURDF

### ISSUE THREAD

**Issue by hyaguchijsk** [seed-solutions/aero-ros-pkg#270]
reported from @chibi314 
Kineticで現状のURDFが動かないという連絡を受けました．

**Comment by hyaguchijsk** [comment]
gazeboで読み込んだ時に特定のcolladaが表示できず，落ちてしまう．
これはinidigoでも起きている？

**Comment by chibi314** [comment]
indigo、kinetic関係なく落ちてしまいます。
デスクトップPC(Core-i7 6コア、 GTX1080Ti)でも落ちてしまうので単に重いということではなくcolladaファイルに問題があるという結論、でいいでしょうか。

**Comment by hyaguchijsk** [comment]
一旦閉じて #116 に戻しましょう
